### ISSUE TITLE
Wakeup from Power Semantic B tests have races.

### ISSUE THREAD

**Issue by hnickvmw** [ARM-software/sbsa-acs#242] opened 2022-06-01 13:39 UTC
Hi,

I noticed that the timer might fire before the val_power_enter_semantic(SBSA_POWER_SEM_B); call and the PE will sleep forever as a result. Maybe the tests should set DAIF before the val_timer_set_* call?

https://github.com/ARM-software/sbsa-acs/blob/2828969157945b6606d96ec84df42828c7cbff88/test_pool/power_wakeup/test_u001.c#L139

**Comment by darkwood101** [comment] 2022-06-08 19:19
The race condition manifests itself on QEMU sbsa-ref, due to the fact that the board is fully software-emulated, and as a result is much slower than real hardware. Increasing the timeout to `TIMEOUT_MEDIUM` works as a quick fix, but does not eliminate the race condition and it does not guarantee correctness. This is also present in `payload2` and `payload3`, except the PE does not sleep forever due to the failsafe interrupt.

**Comment by chetan-rathore** [comment] 2022-06-22 05:17
Hi @darkwood101, 

We are checking the issue and will share updates soon.

Thanks,
ACS

**Comment by chetan-rathore** [comment] 2022-06-27 05:23
Hi @darkwood101, 

Power and wakeup tests have been updated to use system counter frequency as timeout and also command line parameter "timeout" is introduced to increase the timeout in multiple of system frequency if depending on test enviroment the default timeout value is not sufficient as seen in the present case.

Thanks,
ACS

**Comment by darkwood101** [comment] 2022-06-27 13:08
I can confirm that the tests now work for me with the default timeout based on system counter frequency. Thank you!

**Comment by chetan-rathore** [comment] 2022-06-28 06:14
Hi @darkwood101, 

The changes have been merged.

Thanks,
ACS

**Closed** 2022-06-29 17:06 UTC
Labels: enhancement
