### ISSUE TITLE
SBSA peripherals m001_entry

### ISSUE THREAD

**Issue by tingwanyang** [ARM-software/sbsa-acs#103] opened 2020-11-16 07:41 UTC
HI,

I have a question about peripheral m001_entry. In payload function, I found variable named addr which is not Initialized，but used in pal_memory_get_unpopulated_addr function. May I know the reason?

Many thanks
Tingwan

![image](https://user-images.githubusercontent.com/74529631/99225966-e40dad00-2823-11eb-9379-562d2116307b.png)

![image](https://user-images.githubusercontent.com/74529631/99225763-8bd6ab00-2823-11eb-96e8-f45b386b3256.png)

**Comment by edhay** [comment] 2020-11-17 05:02
The issue is fixed by commit id: https://github.com/ARM-software/sbsa-acs/commit/0f662e9011f6985d1e1066613774d8a5a96c72ed

Closing the issue.

**Closed by edhay** 2020-11-17 05:02 UTC
