### ISSUE TITLE
SBSA EFI can't save content into SbsaResults.log - Sized 0KB

### ISSUE THREAD

**Issue by sunnywang-arm** [ARM-software/sbsa-acs#233] opened 2022-05-13 21:41 UTC
Track this issue publicly in case others also run into the same problem. 
The issue is that the SBSA EFI test is done but SbsaResults.log in USB drive shows empty. 
Using UEFI Shell Redirection "Sbsa.efi > SbsaResults.log" works, but using "sbsa.efi -f SbsaResults.log" doesn't work.

**Comment by chetan-rathore** [comment] 2022-06-22 05:20
Hi @sunnywang-arm, 

We are already checking the issue and in process of verifying the fix. We will share the updates on root cause soon.

Thanks,
ACS

**Comment by chetan-rathore** [comment] 2022-07-05 17:30
Hi @sunnywang-arm,

The issue is observed due to smmu init code, it is required only by pcie exerciser test. As a workaround the code is moved inside exerciser test run function.

https://github.com/ARM-software/sbsa-acs/pull/251

Thanks,
ACS

**Comment by chetan-rathore** [comment] 2022-07-06 18:08
Hi @sunnywang-arm,

Changes has been merged.

Thanks,
ACS

**Closed by chetan-rathore** 2022-07-06 18:08 UTC
Labels: bug
