### ISSUE TITLE
TEST on PCIE 030, trapped into ESR and BDF corrupt

### ISSUE THREAD

**Issue by Jingshan-cwm** [ARM-software/sbsa-acs#106] opened 2020-11-27 09:30 UTC
For test PCIE 030, it checked memory BAR space access after disable the address decode. 
My symptoms here is esr triggered, but never return to test, it seems like an infinite trap in the ESR handler,

it may be a compile option related issue,
On EDK source, default GCC build option contains -Os in tools_def.template
 
DEFINE GCC_ALL_CC_FLAGS   = -g -Os -fshort-wchar -fno-builtin -fno-strict-aliasing -Wall -Werror -Wno-array-bounds -include AutoGen.h -fno-common
 
And SBSA used label as value ‘&&’，I supposed optimization need to be disable by default, after disable this option, program can return back.

After fixed ESR return issue, I faced another problem, after return back from ESR, BDF value was corrupt,
I guess the value should be save and restore to prevent corruption by accident,
When I used global variable instead local variable define in payload, the BDF value is OK

**Comment by gowthamsiddarthd** [comment] 2021-06-24 06:54
Hi @Jingshan-cwm,

We are unable to reproduce this issue. Closing this issue now, please reopen this issue if not resolved.

Regards,
Gowtham

**Closed by gowthamsiddarthd** 2021-06-24 06:54 UTC
Labels: question
